import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs'; 
import { Product } from '../models/product.model';

@Injectable({
  providedIn: 'root',
})
export class ProductsService {
  private products: Product[] = [
    {
      id: '1',
      name: 'Автостопом галактикою',
      description: 'Комедійна науково-фантастична серія Дугласа Адамса.',
      price: 15.99,
      imageUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
      category: 'Наукова фантастика',
      rating: 4.5,
      popularity: 100,
      releaseDate: new Date('1979-10-12'),
    },
    {
      id: '2',
      name: 'Гордість і упередження',
      description: 'Роман моралі, написаний Джейн Остін.',
      price: 12.50,
      imageUrl: 'https://covers.openlibrary.org/b/id/8091016-L.jpg',
      category: 'Романтика',
      rating: 4.8,
      popularity: 90,
      releaseDate: new Date('1813-01-28'),
    },
    {
      id: '3',
      name: '1984',
      description: 'Антиутопічний науково-фантастичний роман Джорджа Орвелла.',
      price: 10.00,
      imageUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
      category: 'Антиутопія',
      rating: 4.7,
      popularity: 120,
      releaseDate: new Date('1949-06-08'),
    },
    {
      id: '4',
      name: 'Убити пересмішника',
      description: 'Роман Гарпер Лі, опублікований у 1960 році.',
      price: 14.75,
      imageUrl: 'https://covers.openlibrary.org/b/id/8228691-L.jpg',
      category: 'Художня література',
      rating: 4.9,
      popularity: 110,
      releaseDate: new Date('1960-07-11'),
    },
    {
      id: '5',
      name: 'Кобзар',
      description: 'Збірка поезій Тараса Шевченка — класика української літератури.',
      price: 8.99,
      imageUrl: 'https://covers.openlibrary.org/b/id/9254981-L.jpg',
      category: 'Поезія',
      rating: 5.0,
      popularity: 150,
      releaseDate: new Date('1840-01-01'),
    },
    {
      id: '6',
      name: 'Захар Беркут',
      description: 'Історичний роман Івана Франка про боротьбу з монголо-татарами.',
      price: 9.50,
      imageUrl: 'https://covers.openlibrary.org/b/id/8796095-L.jpg',
      category: 'Історична проза',
      rating: 4.6,
      popularity: 95,
      releaseDate: new Date('1883-01-01'),
    },
    {
      id: '7',
      name: 'Тіні забутих предків',
      description: 'Містичний повість Михайла Коцюбинського, дія якої відбувається в Карпатах.',
      price: 11.00,
      imageUrl: 'https://covers.openlibrary.org/b/id/8332915-L.jpg',
      category: 'Класика',
      rating: 4.4,
      popularity: 85,
      releaseDate: new Date('1911-01-01'),
    },
    {
      id: '8',
      name: 'Степовий бог',
      description: 'Сучасний роман Любка Дереша з елементами фантастики.',
      price: 13.20,
      imageUrl: 'https://covers.openlibrary.org/b/id/11182751-L.jpg',
      category: 'Сучасна проза',
      rating: 4.2,
      popularity: 70,
      releaseDate: new Date('2004-06-01'),
    },
    {
  id: '9',
  name: 'Солодка Даруся',
  description: 'Трагічна історія життя молодої жінки з українського села. Авторка — Марія Матіос.',
  price: 11.90,
  imageUrl: 'https://covers.openlibrary.org/b/id/10099952-L.jpg',
  category: 'Сучасна проза',
  rating: 4.6,
  popularity: 88,
  releaseDate: new Date('2004-01-01'),
},
{
  id: '10',
  name: 'Лісова пісня',
  description: 'Поетична драма-феєрія Лесі Українки про кохання Мавки й Лукаша.',
  price: 9.25,
  imageUrl: 'https://covers.openlibrary.org/b/id/8889911-L.jpg',
  category: 'Драма',
  rating: 4.9,
  popularity: 140,
  releaseDate: new Date('1911-01-01'),
},
{
  id: '11',
  name: 'Фелікс Австрія',
  description: 'Історичний роман Софії Андрухович про життя в Станіславові на початку ХХ ст.',
  price: 13.45,
  imageUrl: 'https://covers.openlibrary.org/b/id/10503344-L.jpg',
  category: 'Історична проза',
  rating: 4.7,
  popularity: 93,
  releaseDate: new Date('2014-10-01'),
},
{
  id: '12',
  name: 'Інтернат',
  description: 'Роман Сергія Жадана про війну на сході України очима вчителя.',
  price: 14.00,
  imageUrl: 'https://covers.openlibrary.org/b/id/9276938-L.jpg',
  category: 'Сучасна проза',
  rating: 4.5,
  popularity: 80,
  releaseDate: new Date('2017-01-01'),
},
{
  id: '13',
  name: 'Місто',
  description: 'Психологічний роман Валер’яна Підмогильного про життя студента в Києві.',
  price: 10.75,
  imageUrl: 'https://covers.openlibrary.org/b/id/8325531-L.jpg',
  category: 'Класика',
  rating: 4.3,
  popularity: 75,
  releaseDate: new Date('1928-01-01'),
},
{
  id: '14',
  name: 'Амадока',
  description: 'Монументальний роман Софії Андрухович про пам’ять, ідентичність і втрати.',
  price: 16.99,
  imageUrl: 'https://covers.openlibrary.org/b/id/10798716-L.jpg',
  category: 'Сучасна проза',
  rating: 4.6,
  popularity: 82,
  releaseDate: new Date('2020-01-01'),
}

  ];

  

  getProducts(): Observable<Product[]> {
    return of(this.products);
  }
}
